name: maven-build
run-name: Run maven up to 'verify' phase and archive JAR

on: [push, pull_request]

jobs:
  maven-build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
    - name: Maven build
      run: mvn -B clean verify
    - uses: actions/upload-artifact@v3
      with:
        name: compiled-jar
        path: target/*.jar
        retention-days: 1
